[package]
name = "mica-dataplane-gpu"
description = "GPU dataplane for MICA"
version = "0.1.0"
authors = ["Haohui Mai <haohui@alt-chain.io>"]
edition = "2018"

[dependencies]
libc = "0.2"

[build-dependencies]
cmake = "0.1"